FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.api.txt /app/requirements.api.txt
COPY ./src/api/main.py /app/src/api/main.py
COPY ./data/processed /app/data/processed
COPY ./data/interim/movies.csv /app/data/interim/movies.csv
COPY ./models /app/models
COPY ./src/models_module_def/model_predict.py /app/src/models_module_def/model_predict.py

RUN pip install -r requirements.api.txt

EXPOSE 8000

CMD fastapi run /app/src/api/main.py
