services:
  - type: web
    name: fastapi
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    envVars:
      - key: PORT
        value: 8000
  
  - type: web
    name: prometheus
    env: docker
    image: prom/prometheus:latest
    plan: free
    envVars:
      - key: PORT
        value: 9090

  - type: web
    name: grafana
    env: docker
    image: grafana/grafana:latest
    plan: free
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: alertmanager
    env: docker
    image: prom/alertmanager:latest
    plan: free
    envVars:
      - key: PORT
        value: 9093