global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8080']
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

# monitoring/prometheus/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'movie_recommendation_app'
    static_configs:
      - targets: ['host.docker.internal:8001', 'host.docker.internal:8002', 'host.docker.internal:8003', 'host.docker.internal:8004']





# monitoring/prometheus/prometheus.yml

# global:
#   scrape_interval: 15s

# scrape_configs:
#   - job_name: 'movie_recommendation_app'
#     static_configs:
#       - targets: ['host.docker.internal:8001', 'host.docker.internal:8002', 'host.docker.internal:8003', 'host.docker.internal:8004']
#Note: Adjust host.docker.internal to localhost or the appropriate hostname if necessary.