apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommender-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-recommender
  template:
    metadata:
      labels:
        app: movie-recommender
    spec:
      containers:
      - name: movie-recommender
        image: your-docker-registry/movie-recommender:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@postgres-service:5432/movierecsys
